forge "http://forge.puppetlabs.com"

mod "puppet-hiera"
mod "puppet-r10k"
mod "puppetlabs-concat"
mod "puppetlabs-stdlib"
mod "puppetlabs-ruby"
mod "puppetlabs-gcc"
mod "puppet-make"
mod "puppetlabs-inifile"
mod "puppetlabs-vcsrepo"
mod "puppetlabs-postgresql"
mod "puppetlabs-git"
mod "gentoo-portage"
